CREATE TABLE IF NOT EXISTS `Usuarios` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`Nombre` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL UNIQUE,
	`Estado` BOOLEAN NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Suscripciones` (
	`Id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`Usuario_id` INTEGER NOT NULL,
	`Fecha_inicio` DATE NOT NULL,
	`Fecha_final` DATE NOT NULL,
	`Estado` BOOLEAN NOT NULL,
	PRIMARY KEY(`Id`)
);


CREATE TABLE IF NOT EXISTS `Canchas` (
	`Id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`Nombre_cancha` VARCHAR(255) NOT NULL UNIQUE,
	`Ubicacion` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`Id`)
);


CREATE TABLE IF NOT EXISTS `Partidos` (
	`Id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	`Fecha` DATETIME NOT NULL,
	`Video` VARCHAR(255) NOT NULL,
	`Cancha_id` INTEGER NOT NULL,
	`Usuario_id` INTEGER NOT NULL,
	PRIMARY KEY(`Id`)
);


ALTER TABLE `Usuarios`
ADD FOREIGN KEY(`id`) REFERENCES `Suscripciones`(`Usuario_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Canchas`
ADD FOREIGN KEY(`Id`) REFERENCES `Partidos`(`Cancha_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Usuarios`
ADD FOREIGN KEY(`id`) REFERENCES `Partidos`(`Usuario_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;